# Generated by Django 4.0.4 on 2022-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=50)),
                ('login_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('is_valid', models.CharField(max_length=1)),
                ('create_by', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('modified_by', models.IntegerField()),
            ],
        ),
    ]
