# Generated by Django 4.0 on 2022-06-02 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndRole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, db_column='MenuName', max_length=200, null=True)),
                ('parent_id', models.IntegerField(blank=True, db_column='ParentId', null=True)),
                ('is_valid', models.IntegerField(blank=True, db_column='IsValid', max_length=1, null=True)),
                ('create_by', models.IntegerField(blank=True, db_column='CreateBy', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='CreateTime', default=django.utils.timezone.now, null=True)),
                ('modified_by', models.IntegerField(blank=True, db_column='ModifiedBy', null=True)),
                ('modified_time', models.DateTimeField(auto_now=True, db_column='ModifiedTime', null=True)),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='RoleForMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(blank=True, db_column='RoleId', null=True)),
                ('menu_id', models.IntegerField(blank=True, db_column='MenuId', null=True)),
            ],
            options={
                'db_table': 'sys_role_for_menu',
            },
        ),
        migrations.CreateModel(
            name='RoleForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_column='UserId', null=True)),
                ('role_id', models.IntegerField(blank=True, db_column='RoleId', null=True)),
            ],
            options={
                'db_table': 'sys_role_for_user',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, db_column='ModifiedTime', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, db_column='ModifiedTime', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_valid',
            field=models.CharField(blank=True, db_column='IsValid', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, db_column='Gender', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_valid',
            field=models.CharField(blank=True, db_column='IsValid', max_length=1, null=True),
        ),
    ]
