# Generated by Django 4.0.4 on 2022-05-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndRole', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='sys_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='sys_user',
        ),
    ]
