# Generated by Django 4.0.4 on 2022-05-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndRole', '0002_alter_role_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_name',
            field=models.CharField(db_column='LoginName', max_length=50),
        ),
    ]
