# Generated by Django 4.0 on 2022-06-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAndRole', '0002_menu_roleformenu_roleforuser_role_modified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_valid',
            field=models.IntegerField(blank=True, db_column='IsValid', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_valid',
            field=models.IntegerField(blank=True, db_column='IsValid', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_name',
            field=models.CharField(blank=True, db_column='LoginName', help_text='登录账号', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_pwd',
            field=models.CharField(blank=True, db_column='Login_pwd', help_text='登录密码', max_length=50, null=True),
        ),
    ]
